#### 1. Create a for loop to iterate through data_arr and print each value in the array

In [1]:
import numpy as np

In [2]:
data_arr = np.linspace(1,50,30)

In [3]:
#Double-click __here__ for the solution.

#<!-- Solution:

for val in data_arr:
    print(val)

#-->

1.0
2.689655172413793
4.379310344827586
6.068965517241379
7.758620689655173
9.448275862068966
11.137931034482758
12.827586206896552
14.517241379310345
16.20689655172414
17.896551724137932
19.586206896551726
21.275862068965516
22.96551724137931
24.655172413793103
26.344827586206897
28.03448275862069
29.724137931034484
31.413793103448278
33.10344827586207
34.793103448275865
36.48275862068966
38.17241379310345
39.862068965517246
41.55172413793103
43.241379310344826
44.93103448275862
46.62068965517241
48.310344827586206
50.0


#### 2. Create a while loop to iterate through the data_arr and print each value in the array

In [4]:
#Double-click __here__ for the solution.

#<!-- Solution:

i=0
while i<30:
    print(data_arr[i])
    i+=1
#-->

1.0
2.689655172413793
4.379310344827586
6.068965517241379
7.758620689655173
9.448275862068966
11.137931034482758
12.827586206896552
14.517241379310345
16.20689655172414
17.896551724137932
19.586206896551726
21.275862068965516
22.96551724137931
24.655172413793103
26.344827586206897
28.03448275862069
29.724137931034484
31.413793103448278
33.10344827586207
34.793103448275865
36.48275862068966
38.17241379310345
39.862068965517246
41.55172413793103
43.241379310344826
44.93103448275862
46.62068965517241
48.310344827586206
50.0


#### 3. Use loops to manually add the values in the array and print the sum of the values. Use the in-built function to verify your answer.


In [6]:
#Double-click __here__ for the solution.

#<!-- Solution:

sumarr = 0
for val in data_arr:
    sumarr = sumarr+val

print(sumarr)

print(sum(data_arr))
#-->

765.0
765.0


#### 4. Use for loop to print the square of even numbers between 2 and 50, both values inclusive

In [7]:
#Double-click __here__ for the solution.

#<!-- Solution:

for val in range(2,51,2):
    print(val**2)
    
#-->

4
16
36
64
100
144
196
256
324
400
484
576
676
784
900
1024
1156
1296
1444
1600
1764
1936
2116
2304
2500


#### 5. Use for loop to find the array elements of `data_arr` in positions which are divisble by 3. Index position 0, will 1st position. 

In [15]:
#Double-click __here__ for the solution.

#<!-- Solution:

for ind in range(3,31,3):
    print(ind-1)
    print(data_arr[ind-1])

#There are other ways in which this can be done too.
print('***')
for ind in range(0,30,3):
    print(ind)
    
    print(data_arr[ind])
#-->

2
4.379310344827586
5
9.448275862068966
8
14.517241379310345
11
19.586206896551726
14
24.655172413793103
17
29.724137931034484
20
34.793103448275865
23
39.862068965517246
26
44.93103448275862
29
50.0
***
0
1.0
3
6.068965517241379
6
11.137931034482758
9
16.20689655172414
12
21.275862068965516
15
26.344827586206897
18
31.413793103448278
21
36.48275862068966
24
41.55172413793103
27
46.62068965517241


#### 6. Use an infinite while loop to print all numbers from 1 to 10.

*Infinite `while` loop is the one where the condition to check is always true. For example, `1<2`

In [16]:
#Double-click __here__ for the solution.

#<!-- Solution:
i=1
while(True):
    print(i)
    i += 1
    if(i>10):
        break
    
#There are other ways in which this can be done too.
#-->

1
2
3
4
5
6
7
8
9
10


#### 7. Use while loop to print all numbers from 50 to 100 except numbers divisible by 3.

In [19]:
#Double-click __here__ for the solution.

#<!-- Solution:

i=49
while(i<100):
    i += 1
    if(i % 3 == 0):
        print(i)
        print("continue**")
        continue
    print(i)


#-->

50
51
continue**
52
53
54
continue**
55
56
57
continue**
58
59
60
continue**
61
62
63
continue**
64
65
66
continue**
67
68
69
continue**
70
71
72
continue**
73
74
75
continue**
76
77
78
continue**
79
80
81
continue**
82
83
84
continue**
85
86
87
continue**
88
89
90
continue**
91
92
93
continue**
94
95
96
continue**
97
98
99
continue**
100


#### 8. Iterate through the array `mynumarr` below and find the number of occurences of each number and store them as a dictionary `dict_count` and print it. 

In [21]:
mynumarr = np.random.randint(1,11,100)
dict_count = {'1':0,'2':0,'3':0,'4':0,'5':0,'6':0,'7':0,'8':0,'9':0,'10':0}


In [22]:
#Double-click __here__ for the solution.

#<!-- Solution:

for i in mynumarr:
    dict_count[str(i)] = dict_count[str(i)]+1
    
print(dict_count)

#-->

{'1': 11, '2': 5, '3': 6, '4': 8, '5': 14, '6': 9, '7': 11, '8': 10, '9': 13, '10': 13}


#### 9. Iterate through dict_count using for loop and print formatted output as below.

`Number of 1s is 10`

In [23]:
#Double-click __here__ for the solution.

#<!-- Solution:

for key in dict_count.keys():
    print("Number of %ss is %s"%(key,dict_count[key]))

#-->

Number of 1s is 11
Number of 2s is 5
Number of 3s is 6
Number of 4s is 8
Number of 5s is 14
Number of 6s is 9
Number of 7s is 11
Number of 8s is 10
Number of 9s is 13
Number of 10s is 13


### Run the following cell before you proceed to exercise 10.

The following dataframe contains points scored by the teams as identified by the column header.

In [27]:
import pandas as pd

arr = np.random.randint(1,100,150).reshape(30,5)
print(arr)
afl_df = pd.DataFrame(arr,columns=['GeelongCats','Hawthorn','RichmondTigers','Collingwood','Magpies'])
afl_df


[[50 87 94 60 17]
 [48 82 54 10 91]
 [61 26  7 10 58]
 [29 89 80 35  8]
 [16 17 91 11 17]
 [66 78 56 20 56]
 [50 83 80  4 36]
 [56 84 36 55 12]
 [31  4 20 71 20]
 [72 66 57 99 77]
 [85 18 55 87 91]
 [64 98 47 36  7]
 [31 75 60 45  7]
 [51 33 63 92 39]
 [ 7 10 78  9 29]
 [10 21 66 99 79]
 [40 77 50 78 14]
 [30 82 56 54 35]
 [71 40 80 38 26]
 [23 37 32 63 34]
 [34 33 71 11 73]
 [73 78 49 63 68]
 [52 44 44 83  8]
 [53 64 53 54 98]
 [56 33 25 75 33]
 [ 2 72 96 35 32]
 [ 3 67 25  7 75]
 [40  2  9 41 66]
 [34 34 52 45 76]
 [76 56 74 46 92]]


GeelongCats  Hawthorn  RichmondTigers  Collingwood  Magpies
0            50        87              94           60       17
1            48        82              54           10       91
2            61        26               7           10       58
3            29        89              80           35        8
4            16        17              91           11       17
5            66        78              56           20       56
6            50        83              80            4       36
7            56        84              36           55       12
8            31         4              20           71       20
9            72        66              57           99       77
10           85        18              55           87       91
11           64        98              47           36        7
12           31        75              60           45        7
13           51        33              63           92       39
14            7        10              78            9       29
15           10        21              66           99       79
16           40        77              50           78       14
17           30        82              56           54       35
18           71        40              80           38       26
19           23        37              32           63       34
20           34        33              71           11       73
21           73        78              49           63       68
22           52        44              44           83        8
23           53        64              53           54       98
24           56        33              25           75       33
25            2        72              96           35       32
26            3        67              25            7       75
27           40         2               9           41       66
28           34        34              52           45       76
29           76        56              74           46       92

#### 10. Print each row in the dataframe using for loop, as a formatted output as follows

```
GeelongCats scored ___________

Hawthorn scored ___________

RichmondTigers scored ___________

Collingwood scored ___________

Magpies scored ___________

```

Leave two lines between each set of output.


In [28]:
#Double-click __here__ for the solution.

#<!-- Solution:

for row in afl_df.iterrows():
    print("\nGeelongCats scored %d"%(row[1][0]))
    print("Hawthorn scored %d"%(row[1][1]))
    print("RichmondTigers scored %d"%(row[1][2]))
    print("Collingwood scored %d"%(row[1][3]))
    print("Magpies scored %d\n"%(row[1][4]))

#-->
#Pandas has iterrows() function that will help you loop through each row of a dataframe. Pandas' iterrows() returns an #iterator containing index of each row and the data in each row as a Series. Since iterrows() returns iterator, we can use #next function to see the content of the iterator.


GeelongCats scored 50
Hawthorn scored 87
RichmondTigers scored 94
Collingwood scored 60
Magpies scored 17


GeelongCats scored 48
Hawthorn scored 82
RichmondTigers scored 54
Collingwood scored 10
Magpies scored 91


GeelongCats scored 61
Hawthorn scored 26
RichmondTigers scored 7
Collingwood scored 10
Magpies scored 58


GeelongCats scored 29
Hawthorn scored 89
RichmondTigers scored 80
Collingwood scored 35
Magpies scored 8


GeelongCats scored 16
Hawthorn scored 17
RichmondTigers scored 91
Collingwood scored 11
Magpies scored 17


GeelongCats scored 66
Hawthorn scored 78
RichmondTigers scored 56
Collingwood scored 20
Magpies scored 56


GeelongCats scored 50
Hawthorn scored 83
RichmondTigers scored 80
Collingwood scored 4
Magpies scored 36


GeelongCats scored 56
Hawthorn scored 84
RichmondTigers scored 36
Collingwood scored 55
Magpies scored 12


GeelongCats scored 31
Hawthorn scored 4
RichmondTigers scored 20
Collingwood scored 71
Magpies scored 20


GeelongCats scored 72
Hawthorn 