#### 1. import the numpy package

Double-click __here__ for the solution.

<!-- Solution:

import numpy as np

-->

#### 2. Create a numpy array named `mynums` with the following values.
`534,798,42,365,832,929,278,190,654,256`

Double-click __here__ for the solution.

<!-- Solution:

mynum = np.array([534,798,42,365,832,929,278,190,654,256])
-->

#### 3. Sort the numpy array `mynums` in ascending order and print it.

Double-click __here__ for the solution.

<!-- Solution:

mynums.sort()
print(mynums)

-->

#### 4. Create an array of numbers name `narr` between 20 50 with incremental value of 5. Print the array.

Double-click __here__ for the solution.

<!-- Solution:

narr = np.arange(20,51,5)
print(narr)


-->

#### 5. Create an numpy array named `zero_array` with 20 zero values. Print the array.

Double-click __here__ for the solution.

<!-- Solution:

zero_array = np.zeros(20)
print(zero_array)
-->

#### 6. Create two dimensional array of size 7X8 filled with value 1.

In [11]:
#Double-click __here__ for the solution.

#<!-- Solution:

#As we know 7X8 is 56. Create an array with 56 ones. 
ones_arr = np.ones(56)
print(ones_arr)

#Reshape the one
ones_arr = ones_arr.reshape(7,8)

print(ones_arr)

#-->

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 7. Find the maximum value of the `mynums` array created in exercise 1

Double-click __here__ for the solution.

<!-- Solution:

mynums.max()

-->

#### 8. Create an array with 100 random number between 0 and 50.
*Hint- Use numpy.random*

In [7]:
#Double-click __here__ for the solution.

#<!-- Solution:
import numpy as np
#np.random.randint(0,51,100)
randarr=np.random.randint(0,51,100)
print(randarr)

#-->

[21 34 35 49 41 29  9 29  7 41 11 15 35 43  8  1  2 44 40  4 45  8 27 44
 20 23 18 10 27 13 30 36 40  0 31 17 20 34  6 37 18 10 12  0  7 27 31 27
 39 10 44 15 35 28  9 40 33 50  8 49 39 22 35 33  1 38 44 22 37  6  6 40
 49 11 35  0  7  2 26 30 33 44 32  8 28  0 48 15 46 10 47 49 36 19 40 46
 32 47 49 27]


#### 9. Print the sum, mean and standard deviation  of the numbers in the array `randarr`

In [8]:
#Double-click __here__ for the solution.

#<!-- Solution:

print('Sum ',randarr.sum())
print('Mean ',randarr.mean())
print('Standard Deviation ',randarr.std())

#-->

Sum  2615
Mean  26.15
Standard Deviation  15.237699957670777


#### 10. Print the number 12th and the 27th number in the array `randarr`

In [9]:
#Double-click __here__ for the solution.

#<!-- Solution:

print(randarr[11])
print(randarr[26])

#-->

15
18
