In [ ]:
#From Python for Data Science Cheat Sheet-NumPy Basics

In [1]:
import numpy as np

In [ ]:
##CREATING ARRAYS

In [2]:
a=np.array((1,2,3))

In [3]:
a.shape #array dimensions

(3,)

In [4]:
len(a) #length of array

3

In [5]:
a.ndim #number of array dimensions

1

In [6]:
a.size # number of array elements

3

In [7]:
a.dtype #data type of array elements

dtype('int32')

In [8]:
a.dtype.name #name of data type

'int32'

In [9]:
a.astype(int) #convert an array to a different type

array([1, 2, 3])

In [10]:
print(a)

[1 2 3]


In [11]:
b=np.array([(1.5,2,3), (4,5,6)], dtype=float) #

In [12]:
b.shape #array dimensions

(2, 3)

In [13]:
len(b) #length of array

2

In [14]:
b.ndim #number of array elements

2

In [15]:
b.size #number of array elements

6

In [16]:
b.dtype #Data type of array elements

dtype('float64')

In [17]:
b.dtype.name #name of data type

'float64'

In [18]:
b.astype(int) #convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [20]:
c=np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float) #

In [21]:
c.shape #Array dimensions #cell [24][25] is 3D array refer to "Python For Data Science Cheat Sheet"

(2, 2, 3)

In [22]:
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [ ]:
##INITIAL PLACEHOLDERS

In [23]:
np.zeros((3,4)) #create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2,3,4),dtype=np.int16) #create array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
###

In [25]:
d=np.arange(10,25,5) #create an array of evenly spaced values(step value)

In [26]:
print(d)

[10 15 20]


In [27]:
d.shape #array dimension

(3,)

In [28]:
len(d) #length of array

3

In [29]:
d.ndim #number of array dimensions

1

In [30]:
d.size #number of array elements

3

In [31]:
d.dtype #data type of array elements

dtype('int32')

In [32]:
d.dtype.name #name of data type

'int32'

In [33]:
d.astype(int)  ##convert an array to a different type

array([10, 15, 20])

In [ ]:
###

In [34]:
np.linspace(0,2,9) #create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
###

In [35]:
e=np.full((2,2),7) #create a constant array

In [36]:
print(e)

[[7 7]
 [7 7]]


In [37]:
f=np.eye(2) #create a 2X2 identity matrix

In [ ]:
###

In [38]:
print(f)

[[1. 0.]
 [0. 1.]]


In [ ]:
###

In [39]:
np.random.random((2,2))#create an array with random values

array([[0.64580407, 0.29307351],
       [0.12840221, 0.16724145]])

In [40]:
np.random.random((2,2)) #create an array with random values

array([[0.82536118, 0.65694209],
       [0.00809616, 0.62338536]])

In [ ]:
###

In [41]:
np.empty((3,2)) #create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [ ]:
## I/O

In [ ]:
###Saving & Loading On Disk

In [ ]:
np.save('my_array',a)

In [60]:
help(np.save)

Help on function save in module numpy:

save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
        File or filename to which the data is saved.  If file is a file-object,
        then the filename is unchanged.  If file is a string or Path, a ``.npy``
        extension will be appended to the filename if it does not already
        have one.
    arr : array_like
        Array data to be saved.
    allow_pickle : bool, optional
        Allow saving object arrays using Python pickles. Reasons for disallowing
        pickles include security (loading pickled data can execute arbitrary
        code) and portability (pickled objects may not be loadable on different
        Python installations, for example if the stored objects require libraries
        that are not available, and not all pickled data is compatible between
        Python 2 and Python 3).
  

In [ ]:
np.savez('array.npz',a,b)

In [ ]:
#

In [ ]:
np.load('my_array.npy')

In [59]:
help(np.load)

Help on function load in module numpy:

load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')
    Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.
    
    .. warning:: Loading files that contain object arrays uses the ``pickle``
                 module, which is not secure against erroneous or maliciously
                 constructed data. Consider passing ``allow_pickle=False`` to
                 load data that is known not to contain object arrays for the
                 safer handling of untrusted sources.
    
    Parameters
    ----------
    file : file-like object, string, or pathlib.Path
        The file to read. File-like objects must support the
        ``seek()`` and ``read()`` methods. Pickled files require that the
        file-like object support the ``readline()`` method as well.
    mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
        If not None, then memory-map the file, using the given mode (see
        `n

In [ ]:
##SAVING & LOADING TEXT FILES

In [ ]:
np.loadtxt("myfile.txt")

In [61]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
        The char

In [ ]:
np.genfromtxt("my_file.csv", delimeter=',')

In [58]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [ ]:
np.savetxt("myarray.txt", delimeter=" ")

In [62]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [ ]:
###DATA TYPES

In [ ]:
np.int64 #signed 64-bit integer types

In [63]:
help(np.int64)

Help on class int64 in module numpy:

class int64(signedinteger)
 |  Signed integer type, compatible with C ``long long``.
 |  Character code: ``'q'``.
 |  Canonical name: ``np.longlong``.
 |  Alias *on this platform*: ``np.int64``: 64-bit signed integer (-9223372036854775808 to 9223372036854775807).
 |  Alias *on this platform*: ``np.intp``: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.
 |  
 |  Method resolution order:
 |      int64
 |      signedinteger
 |      integer
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordi

In [ ]:
np.float32 #standard double-precision floating point

In [64]:
help(np.float32)

Help on class float32 in module numpy:

class float32(floating)
 |  Single-precision floating-point number type, compatible with C ``float``.
 |  Character code: ``'f'``.
 |  Canonical name: ``np.single``.
 |  Alias *on this platform*: ``np.float32``: 32-bit-precision floating-point number type: sign bit, 8 bits exponent, 23 bits mantissa.
 |  
 |  Method resolution order:
 |      float32
 |      floating
 |      inexact
 |      number
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |

In [65]:
np.complex # complex numbers represented by 128 floats

complex

In [66]:
help(np.complex)

Help on class complex in module builtins:

class complex(object)
 |  complex(real=0, imag=0)
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      complex.__format__() -> str
 |      
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 | 

In [ ]:
np.bool #Boolean type storing TRUE and FALSE values 

In [67]:
help(np.bool)

Help on class bool in module builtins:

class bool(int)
 |  bool(x) -> bool
 |  
 |  Returns True when the argument x is true, False otherwise.
 |  The builtins True and False are the only two instances of the class bool.
 |  The class bool is a subclass of the class int, and cannot be subclassed.
 |  
 |  Method resolution order:
 |      bool
 |      int
 |      object
 |  
 |  Methods defined here:
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __or__(self, value, /)
 |      Return self|value.
 |  
 |  __rand__(self, value, /)
 |      Return value&self.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __ror__(self, value, /)
 |      Return value|self.
 |  
 |  __rxor__(self, value, /)
 |      Return value^self.
 |  
 |  __str__(self, /)
 |      Return str(self).
 |  
 |  __xor__(self, value, /)
 |      Return self^value.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__

In [68]:
np.object #Python object type

object

In [69]:
help(np.object)

Help on class object in module builtins:

class object
 |  The most base type



In [73]:
np.string_ #fixed-length string type
help(np.string_)

Help on class bytes_ in module numpy:

class bytes_(builtins.bytes, character)
 |  bytes(iterable_of_ints) -> bytes
 |  bytes(string, encoding[, errors]) -> bytes
 |  bytes(bytes_or_buffer) -> immutable copy of bytes_or_buffer
 |  bytes(int) -> bytes object of size given by the parameter initialized with null bytes
 |  bytes() -> empty bytes object
 |  
 |  Construct an immutable array of bytes from:
 |    - an iterable yielding integers in range(256)
 |    - a text string encoded using the specified encoding
 |    - any object implementing the buffer API.
 |    - an integer
 |  
 |  Method resolution order:
 |      bytes_
 |      builtins.bytes
 |      character
 |      flexible
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |

In [ ]:
np.unicode_ #Fixed-length unicode type

In [74]:
print(np.unicode_)

<class 'numpy.str_'>


In [ ]:
##ARITHMETIC OPERATIONS

In [42]:
g=a-b#subtraction

In [43]:
print(a)

[1 2 3]


In [44]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [45]:
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [46]:
np.subtract(a,b)#subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [47]:
b+a #addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [48]:
a/b #division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [49]:
np.divide(a,b) #division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [50]:
a*b #multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [51]:
np.multiply(a,b) #multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [52]:
np.exp(b) #exponentiation e to the power of b# e^1.5, e^2 etc

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [53]:
np.sqrt(b) #square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
np.sin(a) #print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [55]:
np.cos(b) # element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [56]:
np.log(a) # element-wise natural logaritm

array([0.        , 0.69314718, 1.09861229])

In [57]:
e.dot(f) #dot product

array([[7., 7.],
       [7., 7.]])

In [ ]:
###COMPARISON

In [75]:
a==b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [76]:
print(a)

[1 2 3]


In [77]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [78]:
a<2 #element-wise comparison

array([ True, False, False])

In [79]:
np.array_equal(a,b) #Array-wise comparison

False

In [ ]:
###AGGREGATE FUNCTIONS

In [81]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [82]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [80]:
help(b.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [83]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [89]:
a.mean() #Mean

2.0

In [133]:
help(b.median()) 

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [94]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [130]:
help(np.corrcoef('',''))

TypeError: cannot perform reduce with flexible type

In [123]:
a.corrcoef() 

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [144]:
np.std(b) #Standard deviation

1.5920810978785667

In [ ]:
###COPYING ARRAYS

In [141]:
h=a.view() #create a view of the array with the same data

In [142]:
print (h)

[1 2 3]


In [ ]:
np.copy(a) #create a copy of the array

In [145]:
h=a.copy() #create a deep copy of the array

In [146]:
print(h)

[1 2 3]


In [ ]:
###SORTING ARRAYS

In [147]:
a.sort() #sort an array

In [154]:
print (a)

[1 2 3]


In [155]:
c.sort(axis=0) #Sort the elements of an array's axis

In [156]:
print (c) #3 dimension array

[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


In [ ]:
###SUBSETTING, SLICING, INDEXING

In [ ]:
##Subsetting

In [100]:
print(a)

[1 2 3]


In [101]:
a[2]

3

In [102]:
print (b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [103]:
b[1,2]

6.0

In [ ]:
##Slicing

In [105]:
a[0:2] # select items at index 0 and 1

array([1, 2])

In [106]:
b[0:2,1] #select items at row 0 and 1 in column 1

array([2., 5.])

In [107]:
b[:1] #select all items at row 0(equivalent to b[0:1, :1])

array([[1.5, 2. , 3. ]])

In [108]:
print (b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [109]:
c[1,...] #same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [110]:
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [111]:
a[ : :-1] #reversed array a

array([3, 2, 1])

In [112]:
print (a)

[1 2 3]


In [ ]:
##Boolean Indexing

In [114]:
a[a<2] #select elements from a less than 2

array([1])

In [ ]:
##Fancy Indexing

In [122]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #select elements (1,0), (0,1), (1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [117]:
print (b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [119]:
b[[1,0,1,0]][:,[0,1,2,0]] #select a subset of the matrix's rows

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [ ]:
###ARRAY MANIPULATION

In [ ]:
##Transposing Array, Rows become columns

In [134]:
i=np.transpose(b) # permute array dimensions

In [135]:
print(i)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [ ]:
i.T #Permute array dimensions

In [137]:
print(i.T)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
##Changing Array Shape

In [138]:
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [139]:
g.reshape(3,-2)  #Reshape, but don't change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [140]:
print (g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [ ]:
##Adding/Removing Elements

In [157]:
h.resize((2,6)) #return a new array with shape (2,6)

In [159]:
print(h)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [160]:
np.append(h,g) #append items to an array

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [161]:
np.insert(a, 1, 5) #Insert items in array

array([1, 5, 2, 3])

In [162]:
np.delete(a,[1]) #Delete items from an array

array([1, 3])

In [ ]:
##Combining Arraya

In [163]:
print(a)

[1 2 3]


In [164]:
print (d)

[10 15 20]


In [165]:
np.concatenate((a,d),axis=0) # Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [166]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [167]:
np.vstack((a,b)) # Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [168]:
print(e)

[[7 7]
 [7 7]]


In [169]:
print (f)

[[1. 0.]
 [0. 1.]]


In [171]:
np.r_[e,f] #stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [172]:
np.hatack((e,f)) #Stack arrays horizontally (column-wise)

AttributeError: module 'numpy' has no attribute 'hatack'

In [175]:
help(np.hatack(()))

AttributeError: module 'numpy' has no attribute 'hatack'

In [176]:
print(a)

[1 2 3]


In [178]:
print(d)

[10 15 20]


In [177]:
np.column_stack((a,d)) #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [179]:
print(c)

[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


In [180]:
np.c_[a,d] #create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
##Splitting Arrays

In [181]:
np.hsplit(a,3)  #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [183]:
np.vsplit(c,2) #split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]

In [ ]:
######ASKING FOR HELP

In [191]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [190]:
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |